name: 120customs
services:
- name: web
  source_dir: /
  github:
    repo: your-username/120customs
    branch: main
  run_command: |
    php artisan config:cache &&
    php artisan route:cache &&
    php artisan view:cache &&
    php artisan migrate --force &&
    apache2-foreground
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_NAME
    value: "120 Customs"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: APP_KEY
    value: ${APP_KEY}
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: CACHE_DRIVER
    value: redis
  - key: SESSION_DRIVER
    value: redis
  - key: QUEUE_CONNECTION
    value: redis
  - key: REDIS_HOST
    value: ${redis.HOSTNAME}
  - key: REDIS_PORT
    value: ${redis.PORT}
  - key: REDIS_PASSWORD
    value: ${redis.PASSWORD}

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: basic
  num_nodes: 1

- name: redis
  engine: REDIS
  version: "7"
  size: basic
  num_nodes: 1

static_sites:
- name: assets
  source_dir: /public
  routes:
  - path: /assets
